// Generated by CoffeeScript 1.6.3
(function() {
  var Model, Spider;

  Model = require('./schemas');

  Spider = (function() {
    function Spider() {
      this.Event = Model.Event;
      this.Count = Model.Count;
    }

    Spider.prototype.log = function() {
      return Model.Event.create.apply(Model.Event, arguments);
    };

    Spider.prototype.count = function() {
      return Model.Count.update.apply(Model.Count, arguments);
    };

    Spider.configure = function(options) {
      return Model.init(options);
    };

    return Spider;

  })();

  module.exports = Spider;

}).call(this);
