// Generated by CoffeeScript 1.6.3
(function() {
  var CountSchema, Schema;

  Schema = require('mongoose').Schema;

  module.exports = CountSchema = new Schema({
    user: {
      type: Schema.Types.ObjectId
    },
    email: {
      type: String
    },
    created: {
      type: Date,
      "default": Date.now
    },
    updated: {
      type: Date
    },
    action: {
      type: String
    },
    count: {
      type: Number
    }
  });

}).call(this);
