// Generated by CoffeeScript 1.6.3
(function() {
  var Model, modelMap, mongoose;

  mongoose = require('mongoose');

  Model = module.exports;

  modelMap = {
    event: 'Event',
    count: 'Count'
  };

  Model.readyStatus = 0;

  Model.init = function(options) {
    var Uname, name;
    if (options.mongoose) {
      mongoose = options.mongoose;
    }
    if (options.dbUri) {
      mongoose = mongoose.connect(options.dbUri);
    }
    for (name in modelMap) {
      Uname = modelMap[name];
      if (mongoose.models[Uname]) {
        this.model = mongoose.model(Uname);
      } else {
        this.model = mongoose.model(Uname, require("./" + name));
      }
      Model[Uname] = this.model;
    }
    return Model.readyStatus = 1;
  };

}).call(this);
